[package]
name = "greenbone-scanner-framework"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
time = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
futures = { workspace = true }
signal-hook-tokio = { version = "0.4.0", features = ["futures-v0_3"] }
signal-hook = "0.4.3"

[dev-dependencies]
insta = { workspace = true }
