[package]
name = "nasl-c-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
libgcrypt-sys = { path = "libgcrypt-sys" }

[build-dependencies]
cc = "1.0"
