[package]
name = "nasl-c-lib"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
libcrypt-sys = { path = "libcrypt-sys" }
libopenvas-krb5-sys = { path = "libopenvas-krb5-sys" }

[build-dependencies]
cc = { workspace = true }
