[target.aarch64-unknown-linux-gnu]
dockerfile = "cross_aarch64.Dockerfile"
[target.aarch64-unknown-linux-gnu.env]
passthrough = ["CC=aarch64-linux-gnu-gcc", "CHOST=arm64"]
[target.x86_64-unknown-linux-gnu]
dockerfile = "cross.Dockerfile"
