[package]
name = "nasl-interpreter"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"

[dependencies]
nasl-syntax = {path = "../nasl-syntax"}
storage = {path = "../storage"}
# used for !~ =~ string regex operations
regex = "1"
hmac = "0.12.1"
hex = "0.4.3"
digest = "0.10.6"
md2 = "0.10.2"
md-5 = "0.10.5"
ripemd = "0.1.3"
sha1 = "0.10.5"
sha2 = "0.10.6"
flate2 = "1.0.25"
chrono = { version = "0.4.23", default-features = false, features = ["clock"]}
pcap = "1.0.0"
pnet_base = "0.33.0"
pnet = "0.33.0"
aes = "0.8.2"
ccm = "0.5.0"
cbc = { version = "0.1.2", features = ["alloc"]}
ctr = "0.9.2"
aes-gcm = { version = "0.10.1"}
cmac = "0.7.2"
#libssh-rs = "0.1.8"
libssh-rs = {git = "https://github.com/jjnicola/libssh-rs.git", branch = "userauth-try"}
