name: Build and upload docker images

on:
  push:
    branches: [ master, openvas-20.08, openvas-21.04 ]
  pull_request:
    branches: [ master, openvas-20.08, openvas-21.04 ]

jobs:
  upload-testing:
    name: "Upload testing docker images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find reference branch
        run: |
          echo $GITHUB_BASE_REF
          echo $GITHUB_REF
          if [ -n "$GITHUB_BASE_REF" ];                              \
          then echo "BRANCH=${GITHUB_BASE_REF##*/}" >> $GITHUB_ENV;  \
          else echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV;       \
          fi;                                                        \
      - name: Find version
        run: |
          echo $BRANCH
          if [ $BRANCH = "master" ];                                 \
          then VERSION=master;                                       \
          else VERSION=$(echo "$BRANCH" | sed 's/openvas-//g' -);       \
          fi;
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # this only works with github.ref on push not on pull_request. ;)
      - run: echo "Build and push ${{ github.repository }}-${{ env.VERSION }}-${{matrix.compiler}}-testing"
      - name: Build and push
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          push: true
          tags: ${{ github.repository }}-${{ env.VERSION }}-${{matrix.compiler}}-testing
          file: .docker/testing/Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
            COMPILER=${{matrix.compiler}}

  upload-build:
    needs: upload-testing
    name: "Upload build docker images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find reference branch
        run: |
          echo $GITHUB_BASE_REF
          echo $GITHUB_REF
          if [ -n "$GITHUB_BASE_REF" ];                              \
          then echo "BRANCH=${GITHUB_BASE_REF##*/}" >> $GITHUB_ENV;  \
          else echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV;       \
          fi;                                                        \
      - name: Find version
        run: |
          echo $BRANCH
          if [ $BRANCH = "master" ];                                 \
          then VERSION=master;                                       \
          else VERSION=$(echo "$BRANCH" | sed 's/openvas-//g' -);       \
          fi;
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # this only works with github.ref on push not on pull_request. ;)
      - run: echo "Build and push ${{ github.repository }}-${{ env.VERSION }}-${{matrix.compiler}}-build"
      - name: Build and push
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          push: true
          tags: ${{ github.repository }}-${{ env.VERSION }}-${{matrix.compiler}}-build
          file: .docker/build/Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
            COMPILER=${{matrix.compiler}}
