name: helm-charts
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  API_KEY: changeme
  OPENVASD: 127.0.0.1:8080

jobs:
  openvasd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start a local k8s cluster
        uses: jupyterhub/action-k3s-helm@v3
        with:
          k3s-channel: latest
          metrics-enabled: false
      - name: deploy openvasd
        run: |
          helm uninstall openvasd || true 
          helm install openvasd charts/openvasd/ --values charts/openvasd/values.yaml
          kubectl rollout status --watch --timeout 600s deployment/openvasd
          sleep 5
          helm test openvasd
      - id: smoketest
        run: echo "POD_NAME=$(kubectl get pods |grep openvasd | awk '{print $1;}')" >> $GITHUB_OUTPUT
      - name: forward port
        run: |
          echo "POD_NAME: ${{ steps.smoketest.outputs.POD_NAME }}"
          echo "$(kubectl get pods)"
          #kubectl --namespace default port-forward ${{ steps.smoketest.outputs.POD_NAME }} 8080:3000 &
      - name: smoketest
        working-directory: rust/smoketest
        run: |
          make build run
      - uses: greenbone/actions/helm-build-push@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          chart-name: openvasd
          registry: ${{ vars.IMAGE_REGISTRY }}
          registry-subpath: helm-charts/
          registry-user: ${{ secrets.GREENBONE_BOT }}
          registry-token: ${{ secrets.GREENBONE_BOT_PACKAGES_WRITE_TOKEN }}
