name: "SmokeTest"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nasl-lint:
    name: Smoketest openvas-nasl-lint
    runs-on: ubuntu-latest
    container: ${{ github.repository }}-build:unstable
    steps:
      - name: Check out openvas-scanner
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.16.0'
      - name: build
        run: |
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Run Smoketest linter
        run: |
          make build
          ./run -e ../../build/nasl/openvas-nasl-lint
        working-directory: smoketest_lint
