name: File Header Copyright Year Updater

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1 *' # At 00:00 on day-of-month 1 in January.

permissions:
  contents: write
  pull-requests: write

jobs:
  update-header:
    name: Update file header year
    runs-on: 'ubuntu-latest'
    steps:
    - name: Run update header
      uses: greenbone/actions/update-header@v3
      with:
        directories: nasl misc src tools
        target: main
